// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2021-07-17 13:51:18


@class MPLgCollectAddtoolJsonPostReq;

@interface MPLgCollectAddtoolJsonPostReq : NSObject

@property(nonatomic, strong) NSString *name;
@property(nonatomic, strong) NSString *link;

@end

