// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2021-07-12 13:37:36


@class MPFriendJsonGetReq;

@interface MPFriendJsonGetReq : NSObject

@property(nonatomic, strong) NSString *name;
@property(nonatomic, strong) NSString *pass;

@end

