# mPaaS Pods Begin
plugin "cocoapods-mPaaS"
source "https://code.aliyun.com/mpaas-public/podspecs.git"
mPaaS_baseline '10.1.68'  # 请将 x.x.x 替换成真实基线版本
mPaaS_version_code 39   # This line is maintained by MPaaS plugin automatically. Please don't modify.
# mPaaS Pods End
# ---------------------------------------------------------------------
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mPaas_Poc_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mPaas_Poc_Demo

  mPaaS_pod "mPaaS_Nebula"
  mPaaS_pod "mPaaS_UTDID"
  mPaaS_pod "mPaaS_ScanCode"
  mPaaS_pod "mPaaS_LBS"
  mPaaS_pod "mPaaS_CommonUI"
  mPaaS_pod "mPaaS_TinyApp"
  mPaaS_pod "mPaaS_CDP"
  mPaaS_pod "mPaaS_Share"
  mPaaS_pod "mPaaS_Hotpatch"
  mPaaS_pod "mPaaS_Push"
  mPaaS_pod "mPaaS_RPC"
  mPaaS_pod "mPaaS_ARTVC"
  mPaaS_pod "mPaaS_UTDID"
  mPaaS_pod "MPBaseTest"
  mPaaS_pod "mPaaS_Diagnosis"
  mPaaS_pod "mPaaS_Log"
  mPaaS_pod "mPaaS_Upgrade"
  mPaaS_pod "mPaaS_Sync"
  mPaaS_pod "mPaaS_Config"
  mPaaS_pod "mPaaS_Diagnosis"
  mPaaS_pod "mPaaS_CDP"
end
